Q1. Import Numpy as np, and find out the version.

In [2]:
import numpy as np
print(np.__version__)

1.21.6


Q2. Write a program to create a 1D Array

In [3]:
poggers = np.array([x for x in range(1, 11, 1)])
poggers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Q3. Write a program to create a 2D boolean array

In [4]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Q4. Write a program to find out odd numbers from the 1D array

In [5]:
pog = poggers[poggers % 2 == 1]
pog

array([1, 3, 5, 7, 9])

Q5. Write program to replace elements matching a condition in an array

In [6]:
poggers[poggers % 2 == 1] = -1
poggers


array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

Q6. Write a program to reshape an array

In [7]:
poggers = poggers.reshape(2, -1)
poggers

array([[-1,  2, -1,  4, -1],
       [ 6, -1,  8, -1, 10]])

Q7. Write a program to stack two arrays vertically

In [8]:
gers = np.vstack([pog, poggers])
gers

array([[ 1,  3,  5,  7,  9],
       [-1,  2, -1,  4, -1],
       [ 6, -1,  8, -1, 10]])

Q9. Write a program to remove matching elements from an array

In [9]:
champ = np.setdiff1d(poggers, pog)
champ

array([-1,  2,  4,  6,  8, 10])

Q10. Write a program to find where elements of two arrays match

In [10]:
a = np.array([1, 2, 3, 4, 2, 3, 2, 3, 6, 7, 4, 2, 4, 3, 5, 4, 6, 1, 6, 9, 10])
b = np.array([1, 2, 3, 4, 2, 3, 2, 3, 6, 7, 4, 2, 4, 3, 5, 4, 6, 1, 6, 9, 10])
np.where(a == b)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]),)

Q11: Write program to import a dataset with numbers and texts keeping the text intact in python numpy?


In [24]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


Q12: How to normalize an array so the values range exactly between 0 and 1?

In [28]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
normalizedIris = (sepallength - np.min(sepallength))/(np.max(sepallength)-np.min(sepallength))
normalizedIris

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444,
       0.30555556, 0.08333333, 0.19444444, 0.02777778, 0.16666667,
       0.30555556, 0.13888889, 0.13888889, 0.        , 0.41666667,
       0.38888889, 0.30555556, 0.22222222, 0.38888889, 0.22222222,
       0.30555556, 0.22222222, 0.08333333, 0.22222222, 0.13888889,
       0.19444444, 0.19444444, 0.25      , 0.25      , 0.11111111,
       0.13888889, 0.30555556, 0.25      , 0.33333333, 0.16666667,
       0.19444444, 0.33333333, 0.16666667, 0.02777778, 0.22222222,
       0.19444444, 0.05555556, 0.02777778, 0.19444444, 0.22222222,
       0.13888889, 0.22222222, 0.08333333, 0.27777778, 0.19444444,
       0.75      , 0.58333333, 0.72222222, 0.33333333, 0.61111111,
       0.38888889, 0.55555556, 0.16666667, 0.63888889, 0.25      ,
       0.19444444, 0.44444444, 0.47222222, 0.5       , 0.36111111,
       0.66666667, 0.36111111, 0.41666667, 0.52777778, 0.36111111,
       0.44444444, 0.5       , 0.55555556, 0.5       , 0.58333